### ISSUE TITLE
Download of Álfur hratt does not work

### ISSUE THREAD

**Issue by bnika** [grammatek/simaromur#124]
Attempts to download Álfur hratt run into "DownloadVoiceManager: Server Voice description not available" Error.
Not a permanent error, repeated attempts work (after reloading the app from AndroidStudio, first in debug mode and then delete all data on device and load again via "run").

**Comment by lumpidu** [comment]
I could reproduce this error when trying to download a voice without internet => `No internet available, please connect` => Connecting Internet => try to download again => Boom.

This should be fixed with merging #135.

**Comment by lumpidu** [comment]
Actually, this should be fixed via #136 :)
