### ISSUE TITLE
Feedback AVI

### ISSUE THREAD

**Issue by bnika** [grammatek/simaromur#144]
A collection of items coming in from visually impaired users, primarily regarding the Álfur hratt voice. Create an issue for each item when a corresponding task is clear.

- [ ] not possible to change the speed of Álfur hratt 
- [ ] "click" sound whenever Álfur hratt speaks 'prósent' (%)
- [ ] the phone keyboard still a bit unclear

**Comment by lumpidu** [comment]
Closing, as we have superseded Álfur hratt by Steinn
